using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Speedo
{
    public enum VehicleForm
    {
        CAR,
        PLANE,
        BOAT,
    }
    public enum ServiceID : uint
    {
        RACERTRANSFORMSERVICE = 0x4CA0745A, 
        RACERANIMATION = 0x83F24C56,
        RACENETREPLAY = 0x10CFD81B,
        INVENTORY = 0x936BFD9D,
        EFFECT_SPINOUT = 0x75B29DE3,
        EFFECT_STUN = 0x6914E93D,
        EFFECT_EXPLOSION = 0x83E3AC79,
        EFFECT_HOMINGMISSILE = 0x0F9D846A,
        EFFECT_ICECANNON = 0x1EC5DD59,
        EFFECT_1STPLACEATTACK = 0x01A3B9B7,
        EFFECT_BLAST = 0x6598731E,
        EFFECT_FLIPPY = 0xEEDD8502,
        EFFECT_SQUASH = 0xB13DBE12,
        EFFECT_SLOWDOWNSHUNT = 0x5AFAA828,
        EFFECT_UFO = 0x4BF957C8,
        RACEREFFECTS = 0x9399E88E,
        MOTIONFX_RUMBLE = 0x8668D42,
        RACEAUDIO = 0xA9C60B72,
        TRANSFORMBUTTON = 0x21FB2AA1,
        RACERSTUNT = 0xBAE03249,
        RACERNAVMARKER = 0x3D673CD1,
        RACER_REACTIONS = 0xAA18DF7F,
        RACERHANDOFGOD = 0xB3664617,
        ALLSTARPOWER = 0xB2561018,
        SCORINGMOVESERVICE = 0xA3488136,
        BOOSTSERVICE = 0x16CF11EA,
        DRIFTBOOSTSERVICE = 0x0C86EB0B,
        WEAPONPODMAGNET = 0x0DA7131D,
        ALLSTARCOINMAGNET = 0x36CBC612,
        RACERSLOWDOWNSERVICE = 0x634949A7,
        VEHICLESCALINGSERVICE = 0xEA7ED0C0,
        RACERMARKERSERVICE = 0xAF1D9930,
        WARNINGINDICATOR = 0x3276E890,
        NOVICEPILOTDETECTOR = 0x5DBA16EA,
        RACERMODS = 0xCAAF9B9C,
        RACERCOLLISIONSPHERE = 0x7C0B0EED,
        RACERGHOST = 0xF2065A8B,
        SPECTRESERVICE = 0xAEA26CD4
    }

    public enum Direct3DDevice9FunctionOrdinals : short
    {
        QueryInterface = 0,
        AddRef = 1,
        Release = 2,
        TestCooperativeLevel = 3,
        GetAvailableTextureMem = 4,
        EvictManagedResources = 5,
        GetDirect3D = 6,
        GetDeviceCaps = 7,
        GetDisplayMode = 8,
        GetCreationParameters = 9,
        SetCursorProperties = 10,
        SetCursorPosition = 11,
        ShowCursor = 12,
        CreateAdditionalSwapChain = 13,
        GetSwapChain = 14,
        GetNumberOfSwapChains = 15,
        Reset = 16,
        Present = 17,
        GetBackBuffer = 18,
        GetRasterStatus = 19,
        SetDialogBoxMode = 20,
        SetGammaRamp = 21,
        GetGammaRamp = 22,
        CreateTexture = 23,
        CreateVolumeTexture = 24,
        CreateCubeTexture = 25,
        CreateVertexBuffer = 26,
        CreateIndexBuffer = 27,
        CreateRenderTarget = 28,
        CreateDepthStencilSurface = 29,
        UpdateSurface = 30,
        UpdateTexture = 31,
        GetRenderTargetData = 32,
        GetFrontBufferData = 33,
        StretchRect = 34,
        ColorFill = 35,
        CreateOffscreenPlainSurface = 36,
        SetRenderTarget = 37,
        GetRenderTarget = 38,
        SetDepthStencilSurface = 39,
        GetDepthStencilSurface = 40,
        BeginScene = 41,
        EndScene = 42,
        Clear = 43,
        SetTransform = 44,
        GetTransform = 45,
        MultiplyTransform = 46,
        SetViewport = 47,
        GetViewport = 48,
        SetMaterial = 49,
        GetMaterial = 50,
        SetLight = 51,
        GetLight = 52,
        LightEnable = 53,
        GetLightEnable = 54,
        SetClipPlane = 55,
        GetClipPlane = 56,
        SetRenderState = 57,
        GetRenderState = 58,
        CreateStateBlock = 59,
        BeginStateBlock = 60,
        EndStateBlock = 61,
        SetClipStatus = 62,
        GetClipStatus = 63,
        GetTexture = 64,
        SetTexture = 65,
        GetTextureStageState = 66,
        SetTextureStageState = 67,
        GetSamplerState = 68,
        SetSamplerState = 69,
        ValidateDevice = 70,
        SetPaletteEntries = 71,
        GetPaletteEntries = 72,
        SetCurrentTexturePalette = 73,
        GetCurrentTexturePalette = 74,
        SetScissorRect = 75,
        GetScissorRect = 76,
        SetSoftwareVertexProcessing = 77,
        GetSoftwareVertexProcessing = 78,
        SetNPatchMode = 79,
        GetNPatchMode = 80,
        DrawPrimitive = 81,
        DrawIndexedPrimitive = 82,
        DrawPrimitiveUP = 83,
        DrawIndexedPrimitiveUP = 84,
        ProcessVertices = 85,
        CreateVertexDeclaration = 86,
        SetVertexDeclaration = 87,
        GetVertexDeclaration = 88,
        SetFVF = 89,
        GetFVF = 90,
        CreateVertexShader = 91,
        SetVertexShader = 92,
        GetVertexShader = 93,
        SetVertexShaderConstantF = 94,
        GetVertexShaderConstantF = 95,
        SetVertexShaderConstantI = 96,
        GetVertexShaderConstantI = 97,
        SetVertexShaderConstantB = 98,
        GetVertexShaderConstantB = 99,
        SetStreamSource = 100,
        GetStreamSource = 101,
        SetStreamSourceFreq = 102,
        GetStreamSourceFreq = 103,
        SetIndices = 104,
        GetIndices = 105,
        CreatePixelShader = 106,
        SetPixelShader = 107,
        GetPixelShader = 108,
        SetPixelShaderConstantF = 109,
        GetPixelShaderConstantF = 110,
        SetPixelShaderConstantI = 111,
        GetPixelShaderConstantI = 112,
        SetPixelShaderConstantB = 113,
        GetPixelShaderConstantB = 114,
        DrawRectPatch = 115,
        DrawTriPatch = 116,
        DeletePatch = 117,
        CreateQuery = 118,
    }
}
